Fix exception involving `log.log`